name: Sync Github to Gitee

on:
  push:
    branches: [ main ]  # 你的主分支，二选一
  workflow_dispatch:  # 支持网页手动点击运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror repo to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/zhu-l-y
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_branch: main  # 和上面分支保持一致
